In [92]:
from google.colab import files
uploaded= files.upload()

Saving compensation.csv to compensation (2).csv

In [93]:
import pandas as pd

In [94]:
df= pd.read_csv("compensation.csv")
df

,Timestamp,What is your Current Role?,"If other, please indicate your role here",What is your Level?,How many years of experience do you have in the data Field?,"What industry is your Employer? eg Fintech, Utilities, HR, Gaming, Health etc.",What is your gender,What is your main Tech stack?,"If other, please indicate your tool stack here",What is your monthly Gross Salary in Kes per month?,Any other benefits?,What is your work setup?,Employer Type
0,02/10/2023 20:02:53,Data Analyst,NaN,Mid-Level eg Data Analyst,1yr-2yrs,Education,Female,"Python, SQL, SAS/SPSS, Tableau, Excel",NaN,NaN,Other Company specific Perks not listed above,Full remote,Startup
1,02/10/2023 16:41:24,Data Analyst,NaN,Junior eg Junior Data Analyst,1yr-2yrs,Fintech,Female,"Python, SQL, Excel",NaN,"187,000","Health Insurance, Pension, Mobile Phone",Full remote,Established
2,02/10/2023 19:24:45,Data Analyst,NaN,Junior eg Junior Data Analyst,1yr-2yrs,Health,Female,"Power BI, Excel",NaN,190000,"Health Insurance, Pension, Mobile Credit Top-up",Hybrid- I need to be in the office specific da...,Established
3,02/10/2023 16:42:03,Data Analyst,NaN,Intern,Beginner,Education,Male,"Python, SQL, Tableau, Power BI, Excel, Google ...",NaN,15000,Bonus,Full remote,Startup
4,02/10/2023 17:59:31,Data Analyst,NaN,Intern,Beginner,Azubi Africa,Male,"Python, SQL, R, SAS/SPSS, Tableau, Power BI, M...",NaN,00,"Health Insurance, Stocks, Equity, Mobile Phone...",Full remote,Established
...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,11/07/2025 11:00:04,Data Analyst,NaN,Junior eg Junior Data Analyst,1yr-2yrs,Agrifintech,Female,"SQL, Google Sheets",NaN,60000,Health Insurance,Hybrid- I need to be in the office specific da...,Startup
300,11/07/2025 14:33:30,Data Analyst,NaN,Junior eg Junior Data Analyst,1yr-2yrs,Financial Services Provider,Male,"Python, SQL, Tableau, Power BI, Microsoft Azur...","DOMO, Metabase",120000,"Health Insurance, Bonus",Hybrid- I need to be in the office specific da...,Established
301,11/07/2025 16:10:56,Data Engineer,NaN,Junior eg Junior Data Analyst,Beginner,Finance,Male,"Python, SQL, Microsoft Azure",NaN,273000,"Health Insurance, Equity, Mobile Phone, Mobile...",Full remote,Established
302,11/07/2025 19:06:29,Data Engineer,NaN,Senior Level eg Senior Data Analyst,3yrs-5yrs,Marketplaces,Female,"Python, SQL",NaN,600000,Health Insurance,Full remote,Startup
303,17/12/2025 23:26:04,Data Analyst,NaN,Junior eg Junior Data Analyst,1yr-2yrs,BMO,Female,"Power BI, Excel, Google Sheets",NaN,"50,000","Health Insurance, Mobile Credit Top-up",Full Office,Established

In [95]:
#Listing all columns
list(df.columns)

['Timestamp',
 'What is your Current Role?',
 'If other, please indicate your role here',
 'What is your Level?',
 'How many years of experience do you have in the data Field?',
 'What industry is  your Employer? eg Fintech, Utilities, HR, Gaming, Health etc.',
 'What is your gender',
 'What is your main Tech stack?',
 'If other, please indicate your tool stack here',
 'What is your monthly Gross Salary in Kes per month?',
 'Any other benefits?',
 'What is your work setup?',
 'Employer Type']

In [96]:
#Dropping columns
df= df.drop(columns=['Timestamp'])

In [97]:
#renaming column
df= df.rename( columns={
    'What is your Current Role?':'role',
    'If other, please indicate your role here':'other_role',
    'What is your Level?':'level',
    'How many years of experience do you have in the data Field?': 'year_of_experience',
    'What industry is  your Employer? eg Fintech, Utilities, HR, Gaming, Health etc.': 'industry',
    'What is your gender':'gender',
    'What is your main Tech stack?':'tech_stack',
    'If other, please indicate your tool stack here': 'other_stack',
    'What is your monthly Gross Salary in Kes per month?': 'gross_salary',
    'Any other benefits?': 'other_benefits',
    'What is your work setup?': 'work_setup',
    'Employer Type':'employer_type'
})

In [98]:
#Cleaning "other_role" column
df["other_role"]= df["other_role"].str.title().fillna("")

In [99]:
#Level cleaning

df["level"] = df["level"].replace({
    "Mid-Level  eg Data Analyst": "Mid-level",
    "Junior  eg Junior Data Analyst": "Junior",
    "Manager eg Manager of Analytics": "Manager",
    "Senior Level  eg Senior Data Analyst": "Senior",
    "Lead eg Lead Analyst": "Lead",
})

df["level"].unique()

array(['Mid-level', 'Junior', 'Intern', 'Manager', 'Senior', 'Lead'],
      dtype=object)

In [120]:
#Industry cleaning
industry_mapping = {
    # Education
    "education": "Education",
    "edtech": "Education",
    "school": "Education",
    "research/education": "Education",

    # Fintech
    "fintech": "Fintech",
    "finetech": "Fintech",
    "agrifintech": "Fintech",

    # Banking
    "bank": "Banking",
    "banking": "Banking",

    # Finance
    "finance": "Finance",
    "financial": "Finance",
    "financial services provider": "Finance",
    "business information and credit management": "Finance",

    # Insurance
    "insurance": "Insurance",
    "insurance broker": "Insurance",

    # Pensions
    "finance - pensions": "Pensions",
    "pension administration": "Pensions",

    # Technology
    "it": "Technology",
    "technology": "Technology",
    "machine learning": "Technology",
    "artificial intelligence": "Technology",
    "ai": "Technology",
    "enterprise ai": "Technology",
    "backend development": "Technology",
    "erp": "Technology",
    "digital transformation": "Technology",
    "data annotation": "Technology",
    "sports analytics": "Technology",

    # Telecommunications
    "telecommunications": "Telecommunications",
    "telco": "Telecommunications",

    # FMCG
    "fmcg": "FMCG",
    "fast moving consumer goods": "FMCG",
    "manufacturing (fmcg)": "FMCG",
    "manufacturing, fmcgs": "FMCG",

    # Manufacturing
    "manufacturing": "Manufacturing",

    # Retail
    "retail": "Retail",
    "wholesale and retail": "Retail",
    "production and retail": "Retail",

    # E-commerce
    "e-commerce": "E-commerce",
    "marketplaces": "E-commerce",

    # Government
    "government": "Government",

    # NGO / Non-profit
    "ngo": "NGO / Non-profit",
    "non profit organization": "NGO / Non-profit",
    "non-profit": "NGO / Non-profit",
    "non profit": "NGO / Non-profit",

    # Development
    "development": "NGO / Development",
    "development - ingo": "NGO / Development",
    "international development": "NGO / Development",
    "ingo": "NGO / Development",
    "aid": "NGO / Development",
    "socio-economic development": "NGO / Development",
    "impact": "NGO / Development",

    # Healthcare
    "health": "Healthcare",
    "healtg": "Healthcare",
    "health ngo": "Healthcare",
    "health research": "Healthcare",
    "kemri": "Healthcare",
    "amrec": "Healthcare",

    # Environment
    "environment conservancy": "Environment & Conservation",
    "conservation": "Environment & Conservation",
    "environment": "Environment & Conservation",

    # Energy
    "energy": "Energy",
    "sustainable energy": "Energy",
    "solar": "Energy",
    "power": "Energy",
    "emobility": "Energy",

    # Agriculture
    "agriculture": "Agriculture",
    "aquaculture": "Agriculture",

    # Consulting
    "consulting": "Consulting",
    "consultancy": "Consulting",
    "fmcg consulting": "Consulting",

    # Professional Services
    "professional services (accounting)": "Professional Services",
    "professional body": "Professional Services",
    "business outsourcing processing": "Professional Services",

    # Marketing
    "marketing": "Marketing & Advertising",
    "sales and marketing": "Marketing & Advertising",
    "marketing amd advertising": "Marketing & Advertising",
    "marketing and advertising": "Marketing & Advertising",
    "digital marketing": "Marketing & Advertising",
    "brand & marketing strategy agency.": "Marketing & Advertising",

    # Logistics & Transport
    "logistics": "Logistics & Transport",
    "supply chain": "Logistics & Transport",
    "transport": "Logistics & Transport",
    "aviation": "Logistics & Transport",

    # Automotive
    "automotive industry": "Automotive",

    # Engineering & Construction
    "engineering": "Engineering & Construction",
    "construction": "Engineering & Construction",
    "urban development": "Engineering & Construction",
    "real estate and construction": "Engineering & Construction",

    # Media & Entertainment
    "media": "Media & Entertainment",
    "consumer tech and media": "Media & Entertainment",
    "gaming": "Media & Entertainment",

    # Research
    "research": "Research",
    "market research": "Research",
    "statistics": "Research",

    # Other
    "tourism": "Tourism",
    "religious": "Religious",
    "hr": "Human Resources",
    "business": "Other",
    "personal": "Other",
    "general": "Other",
    "still searching": "Unknown",
    "nill": "Unknown",
    "nil": "Unknown"
}
#Clean column by removing white space and making values lower case
df["industry"] = (
    df["industry"]
    .astype("string")
    .str.strip()
    .str.lower()
)
#maping the values to the industry
df["industry"] = df["industry"].map(industry_mapping).fillna("")
#Visualising unique value
df["industry"].unique()

array(['Education', 'Fintech', '', 'Telecommunications', 'Banking',
       'Technology', 'Retail', 'Government', 'Manufacturing', 'Religious',
       'FMCG', 'Consulting', 'Insurance', 'Energy', 'Agriculture',
       'Finance', 'Research', 'E-commerce', 'Tourism'], dtype=object)

In [101]:
#Filling null with empty string. Usefull for concatenation
df["other_stack"]= df["other_stack"].fillna("")

In [102]:
import pandas as pd

# Start with the gross salary column
salary = df["gross_salary"].astype("string").str.strip()

# Create a clean copy
df["gross_salary_clean"] = salary

# --------------------------------------------------
# 1. Convert USD to KES
# $1 = KES 130
# --------------------------------------------------

usd_mask = salary.str.contains(r"\$|usd", case=False, na=False)
hourly_mask = salary.str.contains(r"per hr", case=False, na=False)

usd_values = (
    salary[usd_mask & ~hourly_mask]
    .str.extract(r"([\d,]+(?:\.\d+)?)", expand=False)
    .str.replace(",", "", regex=False)
)

df.loc[usd_mask & ~hourly_mask, "gross_salary_clean"] = (
    usd_values.astype(float).mul(130).astype(str)
)


# --------------------------------------------------
# 2. Convert EUR to KES
# €1 = KES 150
# --------------------------------------------------

euro_mask = salary.str.contains("euro", case=False, na=False)

euro_values = (
    salary[euro_mask]
    .str.extract(r"([\d,]+(?:\.\d+)?)", expand=False)
    .str.replace(",", "", regex=False)
)

df.loc[euro_mask, "gross_salary_clean"] = (
    euro_values.astype(float).mul(150).astype(str)
)


# --------------------------------------------------
# 3. Convert "2.5 million"
# --------------------------------------------------

million_mask = salary.str.contains("million", case=False, na=False)

million_values = (
    salary[million_mask]
    .str.extract(r"([\d.]+)", expand=False)
)

df.loc[million_mask, "gross_salary_clean"] = (
    million_values.astype(float).mul(1_000_000).astype(str)
)


# --------------------------------------------------
# 4. Remove KES/Ksh formatting and commas
# --------------------------------------------------

df["gross_salary_clean"] = (
    df["gross_salary_clean"]
    .str.replace(",", "", regex=False)
    .str.replace("/-", "", regex=False)
    .str.replace("kshs", "", case=False, regex=False)
    .str.replace("ksh", "", case=False, regex=False)
    .str.replace("kes", "", case=False, regex=False)
    .str.strip()
)


# --------------------------------------------------
# 5. Convert K notation
# 80K -> 80000
# 120K -> 120000
# --------------------------------------------------

k_mask = df["gross_salary_clean"].str.match(
    r"^\d+(?:\.\d+)?k$",
    case=False,
    na=False
)

k_values = (
    df.loc[k_mask, "gross_salary_clean"]
    .str.replace("k", "", case=False, regex=False)
)

df.loc[k_mask, "gross_salary_clean"] = (
    k_values.astype(float).mul(1000).astype(str)
)


# --------------------------------------------------
# 6. Set hourly salaries to NULL
# --------------------------------------------------

df.loc[hourly_mask, "gross_salary_clean"] = pd.NA


# --------------------------------------------------
# 7. Set non-salary responses to NULL
# --------------------------------------------------

missing_values = [
    "nan",
    "Nan",
    "Nill",
    "Nil",
    "Unemployed",
    "Prefer not to say"
]

df["gross_salary_clean"] = df["gross_salary_clean"].replace(
    missing_values,
    pd.NA
)


# --------------------------------------------------
# 8. Convert to numeric
# --------------------------------------------------

df["gross_salary_clean"] = pd.to_numeric(
    df["gross_salary_clean"],
    errors="coerce"
)


# --------------------------------------------------
# 9. Remove zero/negative salaries
# --------------------------------------------------

df.loc[
    df["gross_salary_clean"] <= 0,
    "gross_salary_clean"
] = pd.NA


# --------------------------------------------------
# 10. Convert to nullable integer
# --------------------------------------------------

df["gross_salary_clean"] = df["gross_salary_clean"].astype("Int64")
df["gross_salary"]= df["gross_salary_clean"]
df["gross_salary"].unique()

<IntegerArray>
[  <NA>, 187000, 190000,  15000, 500000, 375000, 335000, 310000, 280000,
 230000,
 ...
  22000,  88000, 210000, 430000, 122118, 220000,  82500,  73000, 273000,
 600000]
Length: 107, dtype: Int64

In [103]:
#Work setup cleaning
df["work_setup"]= df["work_setup"].replace({
    'Hybrid- I need to be in the office specific days in a week': 'Hybrid- Specific office days',
    'Hybrid-I choose my days to go the office': "Hybrid- Choose office days"
})
df["work_setup"].unique()

array(['Full remote', 'Hybrid- Specific office days', 'Full Office',
       'Hybrid- Choose office days'], dtype=object)

In [104]:
#Merging techstacks
df['tech_stack_all']= df['tech_stack']+","+ df['other_stack']

In [105]:
df= df.drop(columns=['gross_salary_clean','tech_stack','other_stack'])

,role,other_role,level,year_of_experience,industry,gender,gross_salary,other_benefits,work_setup,employer_type,tech_stack_all
0,Data Analyst,,Mid-level,1yr-2yrs,Education,Female,<NA>,Other Company specific Perks not listed above,Full remote,Startup,"Python, SQL, SAS/SPSS, Tableau, Excel,"
1,Data Analyst,,Junior,1yr-2yrs,Fintech,Female,187000,"Health Insurance, Pension, Mobile Phone",Full remote,Established,"Python, SQL, Excel,"
2,Data Analyst,,Junior,1yr-2yrs,Healthcare,Female,190000,"Health Insurance, Pension, Mobile Credit Top-up",Hybrid- Specific office days,Established,"Power BI, Excel,"
3,Data Analyst,,Intern,Beginner,Education,Male,15000,Bonus,Full remote,Startup,"Python, SQL, Tableau, Power BI, Excel, Google ..."
4,Data Analyst,,Intern,Beginner,NaN,Male,<NA>,"Health Insurance, Stocks, Equity, Mobile Phone...",Full remote,Established,"Python, SQL, R, SAS/SPSS, Tableau, Power BI, M..."
...,...,...,...,...,...,...,...,...,...,...,...
299,Data Analyst,,Junior,1yr-2yrs,Fintech,Female,60000,Health Insurance,Hybrid- Specific office days,Startup,"SQL, Google Sheets,"
300,Data Analyst,,Junior,1yr-2yrs,Finance,Male,120000,"Health Insurance, Bonus",Hybrid- Specific office days,Established,"Python, SQL, Tableau, Power BI, Microsoft Azur..."
301,Data Engineer,,Junior,Beginner,Finance,Male,273000,"Health Insurance, Equity, Mobile Phone, Mobile...",Full remote,Established,"Python, SQL, Microsoft Azure,"
302,Data Engineer,,Senior,3yrs-5yrs,E-commerce,Female,600000,Health Insurance,Full remote,Startup,"Python, SQL,"
303,Data Analyst,,Junior,1yr-2yrs,NaN,Female,50000,"Health Insurance, Mobile Credit Top-up",Full Office,Established,"Power BI, Excel, Google Sheets,"

In [112]:
#renaming the column
df= df.rename(columns= {'tech_stack_all':'tech_stack'})

In [121]:
#Rearranging the data
df= df[['role', 'other_role', 'gender', 'level', 'year_of_experience', 'industry',
 'employer_type', 'work_setup', 'tech_stack', 'gross_salary', 'other_benefits']]
df

,role,other_role,gender,level,year_of_experience,industry,employer_type,work_setup,tech_stack,gross_salary,other_benefits
0,Data Analyst,,Female,Mid-level,1yr-2yrs,Education,Startup,Full remote,"Python, SQL, SAS/SPSS, Tableau, Excel,",<NA>,Other Company specific Perks not listed above
1,Data Analyst,,Female,Junior,1yr-2yrs,Fintech,Established,Full remote,"Python, SQL, Excel,",187000,"Health Insurance, Pension, Mobile Phone"
2,Data Analyst,,Female,Junior,1yr-2yrs,,Established,Hybrid- Specific office days,"Power BI, Excel,",190000,"Health Insurance, Pension, Mobile Credit Top-up"
3,Data Analyst,,Male,Intern,Beginner,Education,Startup,Full remote,"Python, SQL, Tableau, Power BI, Excel, Google ...",15000,Bonus
4,Data Analyst,,Male,Intern,Beginner,,Established,Full remote,"Python, SQL, R, SAS/SPSS, Tableau, Power BI, M...",<NA>,"Health Insurance, Stocks, Equity, Mobile Phone..."
...,...,...,...,...,...,...,...,...,...,...,...
299,Data Analyst,,Female,Junior,1yr-2yrs,Fintech,Startup,Hybrid- Specific office days,"SQL, Google Sheets,",60000,Health Insurance
300,Data Analyst,,Male,Junior,1yr-2yrs,Finance,Established,Hybrid- Specific office days,"Python, SQL, Tableau, Power BI, Microsoft Azur...",120000,"Health Insurance, Bonus"
301,Data Engineer,,Male,Junior,Beginner,Finance,Established,Full remote,"Python, SQL, Microsoft Azure,",273000,"Health Insurance, Equity, Mobile Phone, Mobile..."
302,Data Engineer,,Female,Senior,3yrs-5yrs,E-commerce,Startup,Full remote,"Python, SQL,",600000,Health Insurance
303,Data Analyst,,Female,Junior,1yr-2yrs,,Established,Full Office,"Power BI, Excel, Google Sheets,",50000,"Health Insurance, Mobile Credit Top-up"

In [122]:
#Writting back data the data
df.to_csv(
    "data_professionals_compensation.csv",
    index=False
)

In [123]:
#Reading clean data
compensation_data= pd.read_csv("data_professionals_compensation.csv")
compensation_data

,role,other_role,gender,level,year_of_experience,industry,employer_type,work_setup,tech_stack,gross_salary,other_benefits
0,Data Analyst,NaN,Female,Mid-level,1yr-2yrs,Education,Startup,Full remote,"Python, SQL, SAS/SPSS, Tableau, Excel,",NaN,Other Company specific Perks not listed above
1,Data Analyst,NaN,Female,Junior,1yr-2yrs,Fintech,Established,Full remote,"Python, SQL, Excel,",187000.0,"Health Insurance, Pension, Mobile Phone"
2,Data Analyst,NaN,Female,Junior,1yr-2yrs,NaN,Established,Hybrid- Specific office days,"Power BI, Excel,",190000.0,"Health Insurance, Pension, Mobile Credit Top-up"
3,Data Analyst,NaN,Male,Intern,Beginner,Education,Startup,Full remote,"Python, SQL, Tableau, Power BI, Excel, Google ...",15000.0,Bonus
4,Data Analyst,NaN,Male,Intern,Beginner,NaN,Established,Full remote,"Python, SQL, R, SAS/SPSS, Tableau, Power BI, M...",NaN,"Health Insurance, Stocks, Equity, Mobile Phone..."
...,...,...,...,...,...,...,...,...,...,...,...
299,Data Analyst,NaN,Female,Junior,1yr-2yrs,Fintech,Startup,Hybrid- Specific office days,"SQL, Google Sheets,",60000.0,Health Insurance
300,Data Analyst,NaN,Male,Junior,1yr-2yrs,Finance,Established,Hybrid- Specific office days,"Python, SQL, Tableau, Power BI, Microsoft Azur...",120000.0,"Health Insurance, Bonus"
301,Data Engineer,NaN,Male,Junior,Beginner,Finance,Established,Full remote,"Python, SQL, Microsoft Azure,",273000.0,"Health Insurance, Equity, Mobile Phone, Mobile..."
302,Data Engineer,NaN,Female,Senior,3yrs-5yrs,E-commerce,Startup,Full remote,"Python, SQL,",600000.0,Health Insurance
303,Data Analyst,NaN,Female,Junior,1yr-2yrs,NaN,Established,Full Office,"Power BI, Excel, Google Sheets,",50000.0,"Health Insurance, Mobile Credit Top-up"